const githubResult = """
{
  "total_count": 6054,
  "incomplete_results": false,
  "items": [
    {
      "login": "Filipe",
      "id": 27786693,
      "node_id": "MDQ6VXNlcjI3Nzg2Njkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/27786693?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Filipe",
      "html_url": "https://github.com/Filipe",
      "followers_url": "https://api.github.com/users/Filipe/followers",
      "following_url": "https://api.github.com/users/Filipe/following{/other_user}",
      "gists_url": "https://api.github.com/users/Filipe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Filipe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Filipe/subscriptions",
      "organizations_url": "https://api.github.com/users/Filipe/orgs",
      "repos_url": "https://api.github.com/users/Filipe/repos",
      "events_url": "https://api.github.com/users/Filipe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Filipe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipedeschamps",
      "id": 4248081,
      "node_id": "MDQ6VXNlcjQyNDgwODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4248081?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipedeschamps",
      "html_url": "https://github.com/filipedeschamps",
      "followers_url": "https://api.github.com/users/filipedeschamps/followers",
      "following_url": "https://api.github.com/users/filipedeschamps/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipedeschamps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipedeschamps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipedeschamps/subscriptions",
      "organizations_url": "https://api.github.com/users/filipedeschamps/orgs",
      "repos_url": "https://api.github.com/users/filipedeschamps/repos",
      "events_url": "https://api.github.com/users/filipedeschamps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipedeschamps/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ocefpaf",
      "id": 950575,
      "node_id": "MDQ6VXNlcjk1MDU3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/950575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ocefpaf",
      "html_url": "https://github.com/ocefpaf",
      "followers_url": "https://api.github.com/users/ocefpaf/followers",
      "following_url": "https://api.github.com/users/ocefpaf/following{/other_user}",
      "gists_url": "https://api.github.com/users/ocefpaf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ocefpaf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ocefpaf/subscriptions",
      "organizations_url": "https://api.github.com/users/ocefpaf/orgs",
      "repos_url": "https://api.github.com/users/ocefpaf/repos",
      "events_url": "https://api.github.com/users/ocefpaf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ocefpaf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipesilva",
      "id": 4172079,
      "node_id": "MDQ6VXNlcjQxNzIwNzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4172079?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipesilva",
      "html_url": "https://github.com/filipesilva",
      "followers_url": "https://api.github.com/users/filipesilva/followers",
      "following_url": "https://api.github.com/users/filipesilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipesilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipesilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipesilva/subscriptions",
      "organizations_url": "https://api.github.com/users/filipesilva/orgs",
      "repos_url": "https://api.github.com/users/filipesilva/repos",
      "events_url": "https://api.github.com/users/filipesilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipesilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
